# https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests

name: reblack
on: [pull_request]
jobs:
  build:
    steps:
      - name: Install psf/black
        run: pip3 install black
      - name: Run black --check .
        run: black --check .
      - name: Run black and push changes
        if: failure()
        run: |
          black .
          git config --global user.name 'reblack'
          git config --global user.email 'cclauss@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "fixup: Format Python code with psf/black"
          git push
